---
apiVersion: v1
kind: Secret
metadata:
  labels:
    app: app-secret
  name: app-secret
stringData: 
  secret.json: |-
    {
      "api_key" : "somesecrethere"
    }

---
apiVersion: v1
kind: Pod
metadata:
  labels:
    app: app-secret
  name: app-secret
spec:
  volumes:
    - name: secret
      configMap:
        name: app-secret
  containers:
    - name: app
      command: ["/bin/sh", "-c"]
      args: ["cat /tmp/secret.json"]
      image: busybox:latest
      volumeMounts:
        - name: secret
          mountPath: "/tmp"
          readOnly: true

---